services:
  mongo-db:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secreto  
    volumes:
      - datos-mongo:/data/db

  backend:
    build:
      context: ./backend
    container_name: contenedor-backend
    ports:
      - "8080:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo-db

  frontend:
    build:
      context: ./momentos-nfl
    container_name: contenedor-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  datos-mongo:
